# Generated by Django 4.1.1 on 2022-09-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscaMedico', '0002_city_dayweek_speciality_state_profile_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=255, verbose_name='endereço'),
        ),
    ]
