# Generated by Django 4.1.1 on 2022-09-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscaMedico', '0003_alter_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
